/**
 * Deprecated provenance-header helper.
 *
 * agentsync used to prepend `<!-- Generated by AgentSync from <path> -->` to
 * every synced markdown file. That broke strict frontmatter parsers
 * (codex 0.130+ refuses any SKILL.md whose first line is not `---`), silently
 * dropping every preset-synced skill for codex/opencode users.
 *
 * The header is gone — synced files are now byte-identical to their source,
 * with provenance carried by `.sync-manifest.json` instead.
 *
 * This module is kept as a deprecated shim so existing test fixtures and
 * downstream callers continue to compile; both functions now return the empty
 * string. Remove on the next breaking-change release.
 */

/**
 * @deprecated returns "" — kept only for call-site compatibility.
 */
export function generateHeader(_sourcePath: string): string {
  return "";
}

/**
 * @deprecated returns content unchanged — kept only for call-site compatibility.
 */
export function prependHeader(content: string, _sourcePath: string): string {
  return content;
}
