/**
 * Generated-by Header
 * Prepends a provenance comment to files written in copy mode,
 * so AI agents know the canonical source to edit.
 */

import { toPosixPath } from "../utils/path-normalization.js";

/**
 * Build an HTML comment header indicating the source of a synced file.
 *
 * @param sourcePath - Human-readable source location
 *   e.g. ".agents/skills/foo/SKILL.md" or "preset:company/file.md"
 */
export function generateHeader(sourcePath: string): string {
  return `<!-- Generated by AgentSync from ${toPosixPath(sourcePath)} — DO NOT EDIT -->\n`;
}

/**
 * Prepend the generated-by header to file content.
 */
export function prependHeader(content: string, sourcePath: string): string {
  return `${generateHeader(sourcePath)}${content}`;
}
