/**
 * Shared file-write helper for sync modules (skills, commands, agents).
 * Supports copy and symlink modes.
 *
 * Output files are byte-identical to their source. Earlier versions prepended
 * a `<!-- Generated by AgentSync -->` comment to markdown files, but it broke
 * strict frontmatter parsers (codex 0.130+ rejects any SKILL.md whose first
 * line is not `---`, silently dropping every preset-synced skill). Provenance
 * lives in `.sync-manifest.json` instead.
 */

import { unlink } from "node:fs/promises";
import * as path from "node:path";
import { copy, ensureDir, symlink } from "../utils/fs.js";

export type SyncMode = "copy" | "link";

/**
 * Write a file using copy or symlink depending on mode.
 *
 * @param sourcePath  - Absolute path to the source file
 * @param destPath    - Absolute path to the destination
 * @param mode        - "copy" or "link"
 * @param _sourceLabel - Unused; retained for call-site compatibility
 */
export async function writeFileByMode(
  sourcePath: string,
  destPath: string,
  mode: SyncMode,
  _sourceLabel?: string,
): Promise<void> {
  await ensureDir(path.dirname(destPath));
  if (mode === "link") {
    try {
      try {
        await unlink(destPath);
      } catch {
        // Ignore ENOENT — file doesn't exist yet
      }
      await symlink(sourcePath, destPath);
      return;
    } catch {
      // Fall back to copy on symlink failure (e.g., Windows without admin)
    }
  }
  await copy(sourcePath, destPath);
}
