/**
 * Shared file-write helper for sync modules (skills, commands, agents).
 * Supports copy and symlink modes.
 *
 * Output files are byte-identical to their source. Earlier versions prepended
 * a `<!-- Generated by AgentSync -->` comment to markdown files, but it broke
 * strict frontmatter parsers (codex 0.130+ rejects any SKILL.md whose first
 * line is not `---`, silently dropping every preset-synced skill). Provenance
 * lives in `.sync-manifest.json` instead.
 */

import { copyFile, unlink } from "node:fs/promises";
import * as path from "node:path";
import { ensureDir, symlink } from "../utils/fs.js";
import { assertSafeProjectFileReplacement } from "../utils/project-output.js";

export type SyncMode = "copy" | "link";

async function unlinkDestination(destPath: string): Promise<void> {
  try {
    await unlink(destPath);
  } catch {
    // Missing paths need no preparation. A directory remains in place so the
    // subsequent file write fails instead of removing content recursively.
  }
}

/**
 * Write a file using copy or symlink depending on mode.
 *
 * @param sourcePath  - Absolute path to the source file
 * @param destPath    - Absolute path to the destination
 * @param mode        - "copy" or "link"
 * @param projectRoot - Project boundary that the destination must remain inside
 */
export async function writeFileByMode(
  sourcePath: string,
  destPath: string,
  mode: SyncMode,
  projectRoot: string,
): Promise<void> {
  await assertSafeProjectFileReplacement(projectRoot, destPath, sourcePath);
  await ensureDir(path.dirname(destPath));
  await unlinkDestination(destPath);
  if (mode === "link") {
    try {
      await symlink(sourcePath, destPath);
      return;
    } catch {
      // Fall back to copy on symlink failure (e.g., Windows without admin)
    }
  }
  // Materialize source bytes. `fs.cp()` preserves a source symlink by default,
  // which would make copy mode emit another link instead of a durable copy.
  await copyFile(sourcePath, destPath);
}
