/**
 * Shared file-write helper for sync modules (skills, commands, agents).
 * Supports copy mode (with generated headers) and symlink mode.
 */

import { readFile, unlink } from "node:fs/promises";
import * as path from "node:path";
import { copy, ensureDir, outputFile, symlink } from "../utils/fs.js";
import { prependHeader } from "./header.js";

export type SyncMode = "copy" | "link";

/**
 * Write a file using copy or symlink depending on mode.
 * In copy mode, markdown files get a "Generated by AgentSync" header.
 *
 * @param sourcePath  - Absolute path to the source file
 * @param destPath    - Absolute path to the destination
 * @param mode        - "copy" or "link"
 * @param sourceLabel - Human-readable source path for the header comment
 */
export async function writeFileByMode(
  sourcePath: string,
  destPath: string,
  mode: SyncMode,
  sourceLabel?: string,
): Promise<void> {
  await ensureDir(path.dirname(destPath));
  if (mode === "link") {
    try {
      // Remove existing file/symlink to avoid EEXIST on subsequent runs
      try {
        await unlink(destPath);
      } catch {
        // Ignore ENOENT — file doesn't exist yet
      }
      await symlink(sourcePath, destPath);
      return;
    } catch {
      // Fall back to copy on symlink failure (e.g., Windows without admin)
    }
  }
  // In copy mode, prepend header to markdown files
  if (sourceLabel && (destPath.endsWith(".md") || destPath.endsWith(".mdc"))) {
    const content = await readFile(sourcePath, "utf-8");
    await outputFile(destPath, prependHeader(content, sourceLabel), {
      encoding: "utf-8",
    });
  } else {
    await copy(sourcePath, destPath);
  }
}
