/**
 * Generated-by Header Tests
 * Verifies that files written in copy mode include the provenance header
 * and that symlink mode does NOT include the header.
 */
import { lstat, mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { syncAgents } from "../../../src/sync/agents.js";
import { syncCommands } from "../../../src/sync/commands.js";
import { generateHeader, prependHeader } from "../../../src/sync/header.js";
import { syncSkills } from "../../../src/sync/skills.js";
import { getToolProvider } from "../../../src/tools/index.js";
import { ensureDir, outputFile } from "../../../src/utils/fs.js";

describe("generateHeader", () => {
  it("produces an HTML comment with the source path", () => {
    const header = generateHeader(".agents/skills/tdd/SKILL.md");
    expect(header).toBe(
      "<!-- Generated by AgentSync from .agents/skills/tdd/SKILL.md \u2014 DO NOT EDIT -->\n",
    );
  });

  it("works with preset source paths", () => {
    const header = generateHeader("preset:company/tdd/SKILL.md");
    expect(header).toContain("preset:company/tdd/SKILL.md");
    expect(header).toContain("DO NOT EDIT");
  });

  it("normalizes Windows separators in source paths", () => {
    const header = generateHeader(".agents\\skills\\tdd\\SKILL.md");
    expect(header).toBe(
      "<!-- Generated by AgentSync from .agents/skills/tdd/SKILL.md \u2014 DO NOT EDIT -->\n",
    );
  });
});

describe("prependHeader", () => {
  it("prepends header before content", () => {
    const content = "---\nname: foo\n---\n# Foo";
    const result = prependHeader(content, ".agents/skills/foo/SKILL.md");
    expect(result).toMatch(
      /^<!-- Generated by AgentSync from .agents\/skills\/foo\/SKILL\.md/,
    );
    expect(result).toContain(content);
  });
});

describe("Generated header in copy mode", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await mkdtemp(path.join(tmpdir(), "agentsync-header-test-"));
  });

  afterEach(async () => {
    await rm(tmpDir, { recursive: true, force: true });
  });

  it("skills in copy mode have the header", async () => {
    const skillDir = path.join(tmpDir, ".agents", "skills", "tdd");
    await ensureDir(skillDir);
    const originalContent = "---\nname: tdd\n---\n# TDD Skill";
    await outputFile(path.join(skillDir, "SKILL.md"), originalContent);

    const providers = [getToolProvider("claude")];
    await syncSkills(providers, tmpDir, undefined, { mode: "copy" });

    const outputPath = path.join(
      tmpDir,
      ".claude",
      "skills",
      "tdd",
      "SKILL.md",
    );
    const written = await readFile(outputPath, "utf-8");
    const expectedHeader = generateHeader(".agents/skills/tdd/SKILL.md");
    expect(written).toBe(expectedHeader + originalContent);
  });

  it("skills in link mode do NOT have the header", async () => {
    const skillDir = path.join(tmpDir, ".agents", "skills", "tdd");
    await ensureDir(skillDir);
    const originalContent = "---\nname: tdd\n---\n# TDD Skill";
    await outputFile(path.join(skillDir, "SKILL.md"), originalContent);

    const providers = [getToolProvider("claude")];
    await syncSkills(providers, tmpDir, undefined, { mode: "link" });

    const outputPath = path.join(
      tmpDir,
      ".claude",
      "skills",
      "tdd",
      "SKILL.md",
    );
    // In link mode the output is a symlink to the source — no header
    const stat = await lstat(outputPath);
    expect(stat.isSymbolicLink()).toBe(true);
    const written = await readFile(outputPath, "utf-8");
    expect(written).toBe(originalContent);
  });

  it("commands in copy mode have the header", async () => {
    const cmdsDir = path.join(tmpDir, ".agents", "commands");
    await ensureDir(cmdsDir);
    const originalContent =
      "---\ndescription: Create commit\n---\n# Commit Command";
    await outputFile(path.join(cmdsDir, "commit.md"), originalContent);

    const providers = [getToolProvider("claude")];
    await syncCommands(providers, tmpDir, undefined, { mode: "copy" });

    const outputPath = path.join(tmpDir, ".claude", "commands", "commit.md");
    const written = await readFile(outputPath, "utf-8");
    const expectedHeader = generateHeader(".agents/commands/commit.md");
    expect(written).toBe(expectedHeader + originalContent);
  });

  it("commands in link mode do NOT have the header", async () => {
    const cmdsDir = path.join(tmpDir, ".agents", "commands");
    await ensureDir(cmdsDir);
    const originalContent =
      "---\ndescription: Create commit\n---\n# Commit Command";
    await outputFile(path.join(cmdsDir, "commit.md"), originalContent);

    const providers = [getToolProvider("claude")];
    await syncCommands(providers, tmpDir, undefined, { mode: "link" });

    const outputPath = path.join(tmpDir, ".claude", "commands", "commit.md");
    const stat = await lstat(outputPath);
    expect(stat.isSymbolicLink()).toBe(true);
    const written = await readFile(outputPath, "utf-8");
    expect(written).toBe(originalContent);
  });

  it("agents in copy mode have the header", async () => {
    const agentsDir = path.join(tmpDir, ".agents", "agents");
    await ensureDir(agentsDir);
    const originalContent = "---\nname: reviewer\n---\n# Reviewer Agent";
    await outputFile(path.join(agentsDir, "reviewer.md"), originalContent);

    const providers = [getToolProvider("claude")];
    await syncAgents(providers, tmpDir, undefined, { mode: "copy" });

    const outputPath = path.join(tmpDir, ".claude", "agents", "reviewer.md");
    const written = await readFile(outputPath, "utf-8");
    const expectedHeader = generateHeader(".agents/agents/reviewer.md");
    expect(written).toBe(expectedHeader + originalContent);
  });

  it("agents in link mode do NOT have the header", async () => {
    const agentsDir = path.join(tmpDir, ".agents", "agents");
    await ensureDir(agentsDir);
    const originalContent = "---\nname: reviewer\n---\n# Reviewer Agent";
    await outputFile(path.join(agentsDir, "reviewer.md"), originalContent);

    const providers = [getToolProvider("claude")];
    await syncAgents(providers, tmpDir, undefined, { mode: "link" });

    const outputPath = path.join(tmpDir, ".claude", "agents", "reviewer.md");
    const stat = await lstat(outputPath);
    expect(stat.isSymbolicLink()).toBe(true);
    const written = await readFile(outputPath, "utf-8");
    expect(written).toBe(originalContent);
  });

  it("preset skills have header with preset: prefix", async () => {
    const presetDir = path.join(tmpDir, "preset-skills", "review");
    await ensureDir(presetDir);
    await outputFile(path.join(presetDir, "SKILL.md"), "# Review Skill");

    const presetSkills = new Map([
      ["company", [path.join(tmpDir, "preset-skills")]],
    ]);

    const providers = [getToolProvider("claude")];
    await syncSkills(providers, tmpDir, presetSkills, { mode: "copy" });

    const outputPath = path.join(
      tmpDir,
      ".claude",
      "skills",
      "company--review",
      "SKILL.md",
    );
    const written = await readFile(outputPath, "utf-8");
    expect(written).toMatch(
      /^<!-- Generated by AgentSync from preset:company\/review\/SKILL\.md/,
    );
  });

  it("preset commands have header with preset: prefix", async () => {
    const presetDir = path.join(tmpDir, "preset-cmds");
    await ensureDir(presetDir);
    await outputFile(path.join(presetDir, "deploy.md"), "# Deploy Command");

    const presetCommands = new Map([["team", [presetDir]]]);

    const providers = [getToolProvider("claude")];
    await syncCommands(providers, tmpDir, presetCommands, { mode: "copy" });

    const outputPath = path.join(
      tmpDir,
      ".claude",
      "commands",
      "team",
      "deploy.md",
    );
    const written = await readFile(outputPath, "utf-8");
    expect(written).toMatch(
      /^<!-- Generated by AgentSync from preset:team\/deploy\.md/,
    );
  });

  it("non-markdown extra files do NOT get a header", async () => {
    const skillDir = path.join(tmpDir, ".agents", "skills", "lint");
    await ensureDir(skillDir);
    await outputFile(path.join(skillDir, "SKILL.md"), "# Lint Skill");
    const jsonContent = '{"rules": {"semi": "error"}}';
    await outputFile(path.join(skillDir, "config.json"), jsonContent);

    const providers = [getToolProvider("claude")];
    await syncSkills(providers, tmpDir, undefined, { mode: "copy" });

    const jsonPath = path.join(
      tmpDir,
      ".claude",
      "skills",
      "lint",
      "config.json",
    );
    const written = await readFile(jsonPath, "utf-8");
    // JSON files should NOT have the HTML comment header
    expect(written).toBe(jsonContent);
  });
});
