import { chmod, copyFile, mkdir, stat } from "node:fs/promises";
import * as path from "node:path";
import type { z } from "zod";
import type { StatuslineConfigSchema } from "../../types/schemas.js";
import { outputFile } from "../../utils/fs.js";
import { toPosixPath } from "../../utils/path-normalization.js";
import {
  assertSafeProjectOutputFile,
  assertSafeProjectOutputPath,
} from "../../utils/project-output.js";

type StatuslineConfig = z.infer<typeof StatuslineConfigSchema>;
type CustomItem = NonNullable<
  NonNullable<StatuslineConfig>["custom_items"]
>[number];

export const CLAUDE_STATUSLINE_ARTIFACTS = "claude:statusline";
const STATUSLINE_DIR = ".claude/statusline";
const STATUSLINE_SCRIPT = `${STATUSLINE_DIR}/render.sh`;

const TEMPLATE_HEADER = `#!/usr/bin/env bash
# Generated by agentsync — do not edit by hand.
# Reads cc statusline JSON from stdin and emits a pipe-delimited footer.
set -euo pipefail
input="$(cat)"

get_field() {
  python3 -c '
import json, sys

data = json.load(sys.stdin)
for candidate in sys.argv[1:]:
    value = data
    for key in candidate.split("."):
        value = value.get(key, "") if isinstance(value, dict) else ""
    if value not in (None, "") and not isinstance(value, (dict, list)):
        print(value)
        break
else:
    print("")
' "$@" <<<"$input" 2>/dev/null || echo ""
}

`;

const ITEM_SNIPPETS: Record<string, string> = {
  model: `parts+=("$(get_field model.display_name model.id)")`,
  cwd: `parts+=("$(get_field workspace.current_dir cwd)")`,
  branch: `parts+=("$(git -C "$(get_field workspace.current_dir cwd)" branch --show-current 2>/dev/null || echo)")`,
  tokens: `parts+=("$(get_field context_window.total_input_tokens)")`,
  cost: `parts+=("$(get_field cost.total_cost_usd)")`,
  agent: `parts+=("$(get_field agent.name)")`,
  session: `parts+=("$(get_field session_id)")`,
  time: `parts+=("$(date +%H:%M)")`,
};

interface CustomItemCheck {
  item: CustomItem;
  source: string;
  destination: string;
  exists: boolean;
}

async function sourceFileExists(filePath: string): Promise<boolean> {
  try {
    return (await stat(filePath)).isFile();
  } catch {
    return false;
  }
}

async function inspectCustomItems(
  statusline: NonNullable<StatuslineConfig>,
  cwd: string,
): Promise<CustomItemCheck[]> {
  return Promise.all(
    (statusline.custom_items ?? []).map(async (item) => {
      const source = path.resolve(cwd, item.command);
      return {
        item,
        source,
        destination: path.join(cwd, STATUSLINE_DIR, "custom", `${item.id}.sh`),
        exists: await sourceFileExists(source),
      };
    }),
  );
}

function customItemSnippet(destination: string, cwd: string): string {
  return `parts+=("$(${toPosixPath(path.relative(cwd, destination))} 2>/dev/null || echo)")`;
}

function renderStatusline(
  statusline: NonNullable<StatuslineConfig>,
  checks: CustomItemCheck[],
  cwd: string,
): string {
  const availableCustomItems = new Set(
    checks.filter(({ exists }) => exists).map(({ item }) => item.id),
  );
  const lines = [
    TEMPLATE_HEADER,
    `parts=()`,
    ...(statusline.items ?? []).map(
      (item) => ITEM_SNIPPETS[item] ?? `parts+=("")`,
    ),
    ...(statusline.custom_items ?? [])
      .filter(({ id }) => availableCustomItems.has(id))
      .map(({ id }) =>
        customItemSnippet(
          path.join(cwd, STATUSLINE_DIR, "custom", `${id}.sh`),
          cwd,
        ),
      ),
    `if ((\${#parts[@]})); then printf -v rendered ' | %s' "\${parts[@]}"; printf '%s\\n' "\${rendered:3}"; else printf '\\n'; fi`,
    // A single-anchor compact payload survives Claude's terminal-width truncation.
    `python3 -c "import json,sys; d=json.loads(sys.argv[1]); cw=d.get('context_window',{}) or {}; cost=d.get('cost',{}) or {}; out={'pct':cw.get('used_percentage'),'in':cw.get('total_input_tokens'),'max':cw.get('context_window_size'),'cost':cost.get('total_cost_usd')}; print('<<ctx>>'+json.dumps({k:v for k,v in out.items() if v is not None}, separators=(',',':')))" "$input" 2>/dev/null || true`,
  ];
  return `${lines.join("\n")}\n`;
}

interface StatuslineProjection {
  value: { type: string; command: string };
  warnings: string[];
  generatedFiles: string[];
  availableCustomItems: string[];
}

async function prepareStatusline(
  statusline: NonNullable<StatuslineConfig>,
  cwd: string,
): Promise<StatuslineProjection & { checks: CustomItemCheck[] }> {
  const renderScript = path.join(cwd, STATUSLINE_SCRIPT);
  await assertSafeProjectOutputFile(cwd, renderScript);
  const checks = await inspectCustomItems(statusline, cwd);
  const generated = checks.filter(
    ({ exists, source, destination }) =>
      exists && source !== path.resolve(destination),
  );
  await Promise.all(
    generated.map(({ destination }) =>
      assertSafeProjectOutputFile(cwd, destination),
    ),
  );

  return {
    value: {
      type: "command",
      command: toPosixPath(path.relative(cwd, renderScript)),
    },
    warnings: checks
      .filter(({ exists }) => !exists)
      .map(
        ({ item }) =>
          `statusline custom_item ${item.id}: source ${item.command} not found`,
      ),
    generatedFiles: [
      renderScript,
      ...generated.map(({ destination }) => destination),
    ],
    availableCustomItems: checks
      .filter(({ exists }) => exists)
      .map(({ item }) => item.id),
    checks,
  };
}

export async function projectClaudeStatusline(
  statusline: NonNullable<StatuslineConfig>,
  cwd: string,
): Promise<StatuslineProjection> {
  const { checks: _checks, ...projection } = await prepareStatusline(
    statusline,
    cwd,
  );
  return projection;
}

export async function writeClaudeStatusline(
  statusline: NonNullable<StatuslineConfig>,
  cwd: string,
): Promise<{ warnings: string[]; generatedFiles: string[] }> {
  const { checks, ...projection } = await prepareStatusline(statusline, cwd);
  const availableCustomItems = new Set(projection.availableCustomItems);
  const generatedFiles: string[] = [];

  for (const { item, source, destination } of checks) {
    if (!availableCustomItems.has(item.id)) continue;
    if (source !== path.resolve(destination)) {
      await assertSafeProjectOutputFile(cwd, destination);
      await mkdir(path.dirname(destination), { recursive: true });
      await copyFile(source, destination);
      await chmod(destination, 0o755);
      generatedFiles.push(destination);
    }
  }

  const scriptPath = path.join(cwd, STATUSLINE_SCRIPT);
  await assertSafeProjectOutputPath(cwd, scriptPath);
  await mkdir(path.dirname(scriptPath), { recursive: true });
  await outputFile(scriptPath, renderStatusline(statusline, checks, cwd), {
    encoding: "utf-8",
  });
  await chmod(scriptPath, 0o755);
  generatedFiles.push(scriptPath);
  return { warnings: projection.warnings, generatedFiles };
}
