/**
 * Claude Code Tool Provider
 */

import { chmod, copyFile, mkdir } from "node:fs/promises";
import * as path from "node:path";
import type { z } from "zod";
import type { MCP } from "../core/mcp/tokens.js";
import type {
  HookSpec,
  OutputStyleConfigSchema,
  PermissionsConfigSchema,
  StatuslineConfigSchema,
} from "../types/schemas.js";
import { outputFile } from "../utils/fs.js";
import { toPosixPath } from "../utils/path-normalization.js";
import { mergeIntoSettings, writeMcpJson } from "./mcp-helpers.js";
import type { ToolProvider } from "./types.js";

type PermissionsConfig = z.infer<typeof PermissionsConfigSchema>;
type StatuslineConfig = z.infer<typeof StatuslineConfigSchema>;
type OutputStyleConfig = z.infer<typeof OutputStyleConfigSchema>;

/**
 * Translate a canonical hook spec into cc's settings.json shape:
 *   { matcher, hooks: [{ type: "command", command, timeout? }] }
 * Copies the canonical script (relative to cwd) into .claude/hooks/scripts/
 * and chmods +x so the cc-side command path resolves at runtime.
 */
async function copyScriptToClaude(
  command: string,
  cwd: string,
): Promise<string> {
  // Only relocate scripts that look like project-relative paths; absolute
  // commands (e.g., "/usr/bin/env") or bare commands stay verbatim.
  if (command.startsWith("/") || !command.includes("/")) return command;
  const source = path.resolve(cwd, command);
  const dest = path.join(
    cwd,
    ".claude",
    "hooks",
    "scripts",
    path.basename(command),
  );
  try {
    await mkdir(path.dirname(dest), { recursive: true });
    await copyFile(source, dest);
    await chmod(dest, 0o755);
  } catch {
    // Source missing — fall back to leaving command as-declared so cc
    // surfaces the misconfiguration at runtime rather than silently dropping.
    return command;
  }
  return toPosixPath(path.relative(cwd, dest));
}

async function writeClaudeHooks(
  hooks: Record<string, HookSpec[]>,
  cwd: string,
): Promise<{ dropped: Array<{ event: string; id: string; reason: string }> }> {
  const dropped: Array<{ event: string; id: string; reason: string }> = [];
  const out: Record<string, Array<Record<string, unknown>>> = {};
  for (const [event, specs] of Object.entries(hooks)) {
    const entries: Array<Record<string, unknown>> = [];
    for (const spec of specs) {
      const command = await copyScriptToClaude(spec.command, cwd);
      const handler: Record<string, unknown> = {
        type: "command",
        command,
      };
      if (spec.timeout) handler.timeout = spec.timeout;
      const entry: Record<string, unknown> = { hooks: [handler] };
      if (spec.matcher) entry.matcher = spec.matcher;
      entries.push(entry);
    }
    out[event] = entries;
  }
  await mergeIntoSettings(
    path.join(cwd, ".claude", "settings.json"),
    out,
    "hooks",
  );
  return { dropped };
}

async function writeClaudePermissions(
  permissions: NonNullable<PermissionsConfig>,
  cwd: string,
): Promise<{ warnings: string[] }> {
  const warnings: string[] = [];
  const allow: string[] = [];
  const ask: string[] = [];
  const deny: string[] = [];
  for (const rule of permissions.rules ?? []) {
    const pattern = rule.pattern ?? "*";
    const claudeRule = `${rule.tool}(${pattern})`;
    if (rule.decision === "allow") allow.push(claudeRule);
    else if (rule.decision === "deny") deny.push(claudeRule);
    else ask.push(claudeRule);
  }
  const out: Record<string, unknown> = { allow, ask, deny };
  // cc's defaultMode vocabulary is {default|acceptEdits|bypassPermissions|plan}.
  // Canonical default is {allow|ask|deny}. Map to the closest cc semantics —
  // ask→default (prompt per action), allow→acceptEdits (auto-accept), deny→plan
  // (read-only). Passing canonical strings through verbatim makes cc emit
  // "Found 1 settings issue" and disable the permissions system entirely.
  if (permissions.default) {
    const DEFAULT_TO_CC: Record<string, string> = {
      ask: "default",
      allow: "acceptEdits",
      deny: "plan",
    };
    out.defaultMode = DEFAULT_TO_CC[permissions.default] ?? "default";
  }
  await mergeIntoSettings(
    path.join(cwd, ".claude", "settings.json"),
    out as Record<string, unknown>,
    "permissions",
  );
  return { warnings };
}

const STATUSLINE_TEMPLATE_HEADER = `#!/usr/bin/env bash
# Generated by agentsync — do not edit by hand.
# Reads cc statusline JSON from stdin and emits a pipe-delimited footer.
set -euo pipefail
input="$(cat)"

get_field() {
  python3 -c "import json,sys; d=json.loads(sys.argv[1]); print(d.get('$1',''))" "$input" 2>/dev/null || echo ""
}

`;

function statuslineItemSnippet(item: string): string {
  switch (item) {
    case "model":
      return `parts+=("$(get_field model_id)")`;
    case "cwd":
      return `parts+=("$(get_field cwd)")`;
    case "branch":
      return `parts+=("$(git -C "$(get_field cwd)" branch --show-current 2>/dev/null || echo)")`;
    case "tokens":
      return `parts+=("$(get_field tokens)")`;
    case "cost":
      return `parts+=("$(get_field cost)")`;
    case "agent":
      return `parts+=("$(get_field agent_id)")`;
    case "session":
      return `parts+=("$(get_field session_id)")`;
    case "time":
      return `parts+=("$(date +%H:%M)")`;
    default:
      return `parts+=("")`;
  }
}

async function writeClaudeStatusline(
  statusline: NonNullable<StatuslineConfig>,
  cwd: string,
): Promise<{ warnings: string[] }> {
  const warnings: string[] = [];
  const items = statusline.items ?? [];
  const customItems = statusline.custom_items ?? [];
  const customDir = path.join(cwd, ".claude", "statusline", "custom");
  if (customItems.length > 0) await mkdir(customDir, { recursive: true });
  const lines = [
    STATUSLINE_TEMPLATE_HEADER,
    `parts=()`,
    ...items.map(statuslineItemSnippet),
  ];
  for (const ci of customItems) {
    const source = path.resolve(cwd, ci.command);
    const dest = path.join(customDir, `${ci.id}.sh`);
    try {
      await copyFile(source, dest);
      await chmod(dest, 0o755);
      lines.push(
        `parts+=("$(${toPosixPath(path.relative(cwd, dest))} 2>/dev/null || echo)")`,
      );
    } catch {
      warnings.push(
        `statusline custom_item ${ci.id}: source ${ci.command} not found`,
      );
    }
  }
  lines.push(`IFS='|' eval 'echo "\${parts[*]/#/ }" | sed "s/| / | /g"'`);
  // Always emit a single-anchor sentinel JSON so an external supervisor can
  // parse current usage from the status line regardless of which canonical
  // items the user enabled. Single anchor (not paired) because cc renders
  // the statusline at terminal width and would truncate a closing marker.
  // Compact JSON keeps the payload under 80 columns.
  lines.push(
    `python3 -c "import json,sys; d=json.loads(sys.argv[1]); cw=d.get('context_window',{}) or {}; cost=d.get('cost',{}) or {}; out={'pct':cw.get('used_percentage'),'in':cw.get('total_input_tokens'),'max':cw.get('context_window_size'),'cost':cost.get('total_cost_usd')}; print('<<ctx>>'+json.dumps({k:v for k,v in out.items() if v is not None}, separators=(',',':')))" "$input" 2>/dev/null || true`,
  );
  const scriptPath = path.join(cwd, ".claude", "statusline", "render.sh");
  await mkdir(path.dirname(scriptPath), { recursive: true });
  await outputFile(scriptPath, `${lines.join("\n")}\n`, { encoding: "utf-8" });
  await chmod(scriptPath, 0o755);
  await mergeIntoSettings(
    path.join(cwd, ".claude", "settings.json"),
    {
      type: "command",
      command: toPosixPath(path.relative(cwd, scriptPath)),
    },
    "statusLine",
  );
  return { warnings };
}

const TONE_TO_CLAUDE: Record<string, string | null> = {
  terse: "Concise",
  pragmatic: null,
  explanatory: "Explanatory",
  friendly: null, // no built-in; user can define a custom style
  none: null,
};

async function writeClaudeOutputStyle(
  outputStyle: NonNullable<OutputStyleConfig>,
  cwd: string,
): Promise<{ warnings: string[] }> {
  const warnings: string[] = [];
  // Copy any custom style files
  if (outputStyle.custom) {
    const stylesDir = path.join(cwd, ".claude", "output-styles");
    await mkdir(stylesDir, { recursive: true });
    for (const custom of outputStyle.custom) {
      const source = path.resolve(cwd, custom.file);
      const dest = path.join(stylesDir, `${custom.name}.md`);
      try {
        await copyFile(source, dest);
      } catch {
        warnings.push(
          `output_style custom ${custom.name}: source ${custom.file} not found`,
        );
      }
    }
  }
  if (outputStyle.tone) {
    const customMatch = outputStyle.custom?.find(
      (c) => c.name === outputStyle.tone,
    );
    const resolved = customMatch
      ? customMatch.name
      : TONE_TO_CLAUDE[outputStyle.tone];
    if (resolved) {
      await mergeIntoSettings(
        path.join(cwd, ".claude", "settings.json"),
        resolved,
        "outputStyle",
      );
    } else {
      warnings.push(
        `output_style tone="${outputStyle.tone}" has no Claude Code built-in; ` +
          `define [[output_style.custom]] with name="${outputStyle.tone}" ` +
          `to ship one, or use tone="terse" or "explanatory".`,
      );
    }
  }
  return { warnings };
}

export const claudeProvider: ToolProvider = {
  name: "claude",
  displayName: "Claude Code",
  paths: {
    skillsDir: ".claude/skills",
    commandsDir: ".claude/commands",
    agentsDir: ".claude/agents",
    mcpConfigPath: ".mcp.json",
    docsFile: "CLAUDE.md",
  },
  capabilities: {
    skills: true,
    commands: true,
    agents: true,
    mcpStdio: true,
    mcpHttp: true,
    nativeAgentsMd: false,
    nativeSkillsDiscovery: false,
    hooks: true,
    permissions: true,
    statusline: true,
    outputStyle: true,
  },
  readsAgentsDir: false,
  agentFileExtension: ".md",
  mcpFormat: {
    async writeMCP(mcps: Record<string, MCP>, cwd: string): Promise<void> {
      await writeMcpJson(path.join(cwd, ".mcp.json"), mcps);
    },
  },
  docsFormat: {
    async writeDocs(_agentsMdPath: string, cwd: string): Promise<void> {
      const claudeMd = path.join(cwd, "CLAUDE.md");
      await outputFile(claudeMd, "@AGENTS.md\n", { encoding: "utf-8" });
    },
  },
  hooksFormat: {
    writeHooks: writeClaudeHooks,
  },
  permissionsFormat: {
    writePermissions: writeClaudePermissions,
  },
  statuslineFormat: {
    writeStatusline: writeClaudeStatusline,
  },
  outputStyleFormat: {
    writeOutputStyle: writeClaudeOutputStyle,
  },
};
